### ISSUE TITLE
Support for channel invitations

### ISSUE THREAD

**Issue by kxz** [kxz/omnipresence#7]
Just like it says on the tin. Channels will need to be whitelisted for invitation, probably with a new `accept_invites` option that works like so:

``` yaml
set accept_invites: on  # accept invites to all channels on server
channel knownbad:
  set accept_invites: off  # except this one known to be problematic
```
